### ISSUE TITLE
error after installation of zip release file

### ISSUE THREAD

**Issue by hartenthaler** [iyoua/Family-Trees-List#1]
After installing your moule I get an error. 
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'wt_gedcom.gedcom_id' in 'where clause' (SQL: select `test_gedcom`.`gedcom_name`, (SELECT setting_value FROM wt_gedcom_setting WHERE gedcom_id = wt_gedcom.gedcom_id AND setting_name = 'title') AS Title, (SELECT COUNT(*) FROM wt_individuals WHERE i_file = wt_gedcom.gedcom_id) AS Individuals, (SELECT COUNT(*) FROM wt_families WHERE f_file = wt_gedcom.gedcom_id) AS Families, (SELECT COUNT(*) FROM wt_dates WHERE d_file = wt_gedcom.gedcom_id) AS Events, (SELECT COUNT(DISTINCT n_surn) FROM wt_name WHERE n_file = wt_gedcom.gedcom_id) AS Surnames from `test_gedcom` where `test_gedcom`.`gedcom_id` > 0 order by `Individuals` desc) …/vendor/illuminate/database/Connection.php:712
#0 …/vendor/illuminate/database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback()
#1 …/vendor/illuminate/database/Connection.php(359): Illuminate\Database\Connection->run()
#2 …/vendor/illuminate/database/Query/Builder.php(2413): Illuminate\Database\Connection->select()
#3 …/vendor/illuminate/database/Query/Builder.php(2402): Illuminate\Database\Query\Builder->runSelect()
#4 …/vendor/illuminate/database/Query/Builder.php(2936): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#5 …/vendor/illuminate/database/Query/Builder.php(2401): Illuminate\Database\Query\Builder->onceWithColumns()
#6 …/modules_v4/family-trees-list/TreesListModule.php(160): Illuminate\Database\Query\Builder->get()
#7 …/resources/views/tree-page-block.phtml(20): TreesListModule\TreesListModule->getBlock()
```

**Comment by iyoua** [comment]
My data table prefix is "wt_", you may need to change it to your data table prefix, such as “wtgh_”。

**Comment by iyoua** [comment]
The errors in the data table and link routing have been fixed.

**Comment by hartenthaler** [comment]
Now I installed your version 1.0.2.

By the way: I do not understand your message "My data table prefix is "wt_", you may need to change it ..."
You should use the data table prefix in your code as it is defined in the configuration of the webtrees user.

Maybe that is the reason for the error which is now shown:
```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'DB4007214.wtgh_gedcom_setting' doesn't exist (SQL: select `test_gedcom`.`gedcom_name`, (SELECT setting_value FROM wtgh_gedcom_setting WHERE gedcom_id = wtgh_gedcom.gedcom_id AND setting_name = 'title') AS Title, (SELECT COUNT(*) FROM wtgh_individuals WHERE i_file = wtgh_gedcom.gedcom_id) AS Individuals, (SELECT COUNT(*) FROM wtgh_families WHERE f_file = wtgh_gedcom.gedcom_id) AS Families, (SELECT COUNT(*) FROM wtgh_dates WHERE d_file = wtgh_gedcom.gedcom_id) AS Events, (SELECT COUNT(DISTINCT n_surn) FROM wtgh_name WHERE n_file = wtgh_gedcom.gedcom_id) AS Surnames from `test_gedcom` where `test_gedcom`.`gedcom_id` > 0 order by `Individuals` desc) …/vendor/illuminate/database/Connection.php:712
#0 …/vendor/illuminate/database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback()
```

**Comment by iyoua** [comment]
I forgot this: everyone's data table prefix may be different. Based on your current error, your data table prefix should be "test_". But I need to solve this problem by letting the module know what the user's data table prefix is, so that it automatically adapts to each user who installs it.
Thank you for testing and discovering this error. I will take some time to fix this error next.

&nbsp;


铁水
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hermann ***@***.***&gt;; 
发送时间: 2024年5月14日(星期二) 凌晨3:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [iyoua/Family-Trees-List] error after installation of zip release file (Issue #1)














 
Now I installed your version 1.0.2.
 
By the way: I do not understand your message "My data table prefix is "wt_", you may need to change it ..."
 You should use the data table prefix in your code as it is defined in the configuration of the webtrees user.
 
Maybe that is the reason for the error which is now shown:
 SQLSTATE[42S02]: Base table or view not found: 1146 Table 'DB4007214.wtgh_gedcom_setting' doesn't exist (SQL: select `test_gedcom`.`gedcom_name`, (SELECT setting_value FROM wtgh_gedcom_setting WHERE gedcom_id = wtgh_gedcom.gedcom_id AND setting_name = 'title') AS Title, (SELECT COUNT(*) FROM wtgh_individuals WHERE i_file = wtgh_gedcom.gedcom_id) AS Individuals, (SELECT COUNT(*) FROM wtgh_families WHERE f_file = wtgh_gedcom.gedcom_id) AS Families, (SELECT COUNT(*) FROM wtgh_dates WHERE d_file = wtgh_gedcom.gedcom_id) AS Events, (SELECT COUNT(DISTINCT n_surn) FROM wtgh_name WHERE n_file = wtgh_gedcom.gedcom_id) AS Surnames from `test_gedcom` where `test_gedcom`.`gedcom_id` &gt; 0 order by `Individuals` desc) …/vendor/illuminate/database/Connection.php:712 #0 …/vendor/illuminate/database/Connection.php(672): Illuminate\Database\Connection-&gt;runQueryCallback()

**Comment by iyoua** [comment]
Finally done. Through the development of this module, I have learned a lot of new knowledge! Thank you!

**Comment by hartenthaler** [comment]
Now your module is working for me! Great job! Well done!
