### ISSUE TITLE
Undefined array key

### ISSUE THREAD

**Issue by hartenthaler** [iyoua/Family-Trees-List#10]
Undefined array key 17 …/modules_v4/family-trees-list/resources/views/list.phtml:22
#0 …/modules_v4/family-trees-list/resources/views/list.phtml(22): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}()

**Comment by iyoua** [comment]
I checked my code and didn't find anything wrong. I have uploaded a new version and both of my testing websites are running normal code. Please try the new version again.

**Comment by iyoua** [comment]
I suspect there is a problem here. Please modify this function and test it again. Thank you!
`private function totalEvents(): array  
{  
    return DB::table('dates')    
        ->select('d_file as gedcom_id', DB::raw('COUNT(*) as count'))  // 直接在SQL中重命名d_file为gedcom_id  
        ->whereNotIn('d_fact', ['HEAD', 'CHAN'])    
        ->groupBy('d_file')    
        ->pluck('count', 'gedcom_id') // 使用gedcom_id作为键名  
        ->all();  
}`

**Comment by iyoua** [comment]
ttreeslistmodule.php line:143

**Comment by iyoua** [comment]
Hi, perhaps you should download the latest version from my last Releases. The files in the main branch were manually updated by me, and sometimes there are inconsistencies in the versions without updates. I deeply apologize for any confusion caused to you!

**Comment by iyoua** [comment]
I guessed that the error might be due to an issue with the statistical results of the data table, so I repeated your mistake: when the number of events in a tree is 0, the array is missing the index of that tree, and the program will make an error. Next, I will find a way to overcome this bug
&nbsp;


铁水
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hermann ***@***.***&gt;; 
发送时间: 2024年5月22日(星期三) 晚上7:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [iyoua/Family-Trees-List] Undefined array key (Issue #10)















我测试现在使用您通过电子邮件发送给我的代码。错误仍然存在。在我的生产系统中，一切正常。在我的测试系统中，错误仍然存在。我通过修改capsule.phtml（第90行左右）来排除一些"$tree-&gt;id（）"来"修复"它:
<?php 如果（$ tree -》 id （）《》 17 &amp;&amp;$ tree -&gt; id ()&gt; 10 :?&gt;< img src =“<?=e($eventicon)?&gt;《？ php echo I18N ：： translate （“事件”）；？》《类=缩放》《？=数（ intval （$ events [$ tree -&gt; id ()]））？》《/ div 》《？您的位置:&gt;
$events中的一些数组键不存在：17、10，还有一些低于10的数组键。我检查了我的数据库:在"test_dates"表中，d_file的值是18,16,...但是没有d_file的值是17。因此阵列键17没有被设置。也许你应该检查所有的数组键，如果它们不存在，就把它们设置为0。或者应该在.ph tml视图文件中测试它们的存在。

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
你收到这个是因为你发表了评论。消息ID:< iyoua /家谱/问题/ 10 / ***@***.***和&gt;

**Comment by iyoua** [comment]
Just update the event statistics function:
`    private function totalEvents(): array  
        {  
        $allFiles = DB::table('gedcom')->select('gedcom_id')->distinct()->pluck('gedcom_id')->all();  
        $eventCounts = DB::table('dates')  
        ->select('d_file as gedcom_id', DB::raw('COUNT(*) as count'))  
        ->whereNotIn('d_fact', ['HEAD', 'CHAN'])  
        ->groupBy('d_file')  
        ->pluck('count', 'gedcom_id')  
        ->all();  
         $result = [];  
        foreach ($allFiles as $gedcomId) {  
           $result[$gedcomId] = $eventCounts[$gedcomId] ?? 0;
         }  
        return $result;  
        }`
